include csrchdlg.asm
include tpxy.asm
include slctfile.asm
include setbmc.asm
include ofcb.asm
include tbar.asm
include edproc.asm
include ectrl.asm
include mrgfile.asm
include confrm.asm
include strmout.asm
include schproc.asm
include strmin.asm
include status.asm
include savefn.asm
include getfn.asm
include txtfnd.asm
include sfcb.asm
