CommandLine   dd ?
hToolBar      dd ?
hWnd          dd ?
hCheck2       dd ?
hCheck1       dd ?
CaseFlag      dd ?
CtrlFlag      dd ?
hMnu          dd ?
TextLen       dd ?
hToolTips     dd ?
lpfnhEditProc dd ?
hIcon         dd ?
hTbBmp        dd ?
hRichEd       dd ?
WholeWord     dd ?
hInstance     dd ?
hStatus       dd ?
