; l33t directives
M0d31		EQU	.Model
Squ1zhed	EQU	Flat
C0113ctC411	EQU	StdCall
inc100d		EQU	include
inc100dl1b	EQU	includelib
c00d		EQU	.code
cr4p		EQU	.data
junk		EQU	.data?
addie		EQU	ADDR
oFfZ		EQU	offset
pr0070		EQU	PROTO
pr0ccie		EQU	PROC
sh4ddup		EQU	ENDP

t00n1bbu12	EQU	byte
s14ng 		EQU	word
munch		EQU	db
sh0rt13		EQU	dw
b1gg13		EQU	dd

r04ds1gn	EQU	ptr
arr0w		EQU	ptr

z1lch		EQU	0

d00			EQU	INVOKE
dew			EQU	INVOKE

; d0p3 0pc0dez
add0r		EQU	add
b4ck		EQU	ret
bl0w		EQU push
p00sh		EQU	push
j4nk		EQU	pop
suck		EQU	pop
dr4g		EQU	mov
h0ll3r		EQU	call
r0l0r		EQU	rol
X0r			EQU	xor
l34			EQU	lea
inc0r		EQU	inc
ch3ck0r		EQU	cmp
l34p		EQU	jmp

; r3g1sturz
e4x			EQU	eax
eZx			EQU	ecx
EdIcz		EQU	edx
