; SUP = SUPERSCRIPT
; SUB = SUBSCRIPT

 SUP_ZERO                   EQU 2070h
 SUP_LATIN_SMALL_LETTER_I   EQU 2071h
 SUP_FOUR                   EQU 2074h
 SUP_FIVE                   EQU 2075h
 SUP_SIX                    EQU 2076h
 SUP_SEVEN                  EQU 2077h
 SUP_EIGHT                  EQU 2078h
 SUP_NINE                   EQU 2079h
 SUP_PLUS_SIGN              EQU 207Ah
 SUP_MINUS                  EQU 207Bh
 SUP_EQUALS_SIGN            EQU 207Ch
 SUP_LEFT_PARENTHESIS       EQU 207Dh
 SUP_RIGHT_PARENTHESIS      EQU 207Eh
 SUP_LATIN_SMALL_LETTER_N   EQU 207Fh
 
 SUB_ZERO                   EQU 2080h
 SUB_ONE                    EQU 2081h
 SUB_TWO                    EQU 2082h
 SUB_THREE                  EQU 2083h
 SUB_FOUR                   EQU 2084h
 SUB_FIVE                   EQU 2085h
 SUB_SIX                    EQU 2086h
 SUB_SEVEN                  EQU 2087h
 SUB_EIGHT                  EQU 2088h
 SUB_NINE                   EQU 2089h
 SUB_PLUS_SIGN              EQU 208Ah
 SUB_MINUS                  EQU 208Bh
 SUB_EQUALS_SIGN            EQU 208Ch
 SUB_LEFT_PARENTHESIS       EQU 208Dh
 SUB_RIGHT_PARENTHESIS      EQU 208Eh
 SUB_SMALL_LETTER_A         EQU 2090h
 SUB_SMALL_LETTER_E         EQU 2091h
 SUB_SMALL_LETTER_O         EQU 2092h
 SUB_SMALL_LETTER_X         EQU 2093h
 SUB_SMALL_LETTER_SCHWA     EQU 2094h
 SUB_SMALL_LETTER_H         EQU 2095h
 SUB_SMALL_LETTER_K         EQU 2096h
 SUB_SMALL_LETTER_L         EQU 2097h
 SUB_SMALL_LETTER_M         EQU 2098h
 SUB_SMALL_LETTER_N         EQU 2099h
 SUB_SMALL_LETTER_P         EQU 209Ah
 SUB_SMALL_LETTER_S         EQU 209Bh
 SUB_SMALL_LETTER_T         EQU 209Ch
  



